FROM ghcr.io/foundry-rs/foundry:v1.0.0 as foundry

FROM ghcr.io/oasysgames/oasys-opstack/op-migrate:op-migrate

RUN apt update
RUN apt install -y curl jq
COPY --from=foundry /usr/local/bin/cast /usr/local/bin/
