FROM --platform=linux/amd64 ghcr.io/foundry-rs/foundry:nightly-51b75c83045a963a48f9cd8d765e0f2e775acb3e as foundry

FROM ghcr.io/oasysgames/oasys-opstack/op-migrate:op-migrate

RUN apt update
RUN apt install -y curl jq
COPY --from=foundry /usr/local/bin/cast /usr/local/bin/
