version: '3'

x-common: &common
  logging:
    driver: json-file
    options:
      max-size: 128m
      max-file: 4
  extra_hosts:
    - host.docker.internal:host-gateway

x-oneshot: &oneshot
  # prevent startup with `docker-compose up -d`
  profiles:
    - oneshot

services:
  replica:
    <<: *common
    image: ghcr.io/oasysgames/oasys-optimism/l2geth:op-migrate
    restart: always
    stop_grace_period: 86400s
    entrypoint: /bin/sh /upgrade/scripts/l2geth.sh
    env_file: .env
    environment:
      # General
      DATADIR: /root/.ethereum
      NETWORK_ID: $L2_CHAIN_ID
      CHAIN_ID: $L2_CHAIN_ID
      BLOCK_SIGNER_ADDRESS: $BLOCK_SIGNER_ADDRESS
      BLOCK_SIGNER_KEY: $BLOCK_SIGNER_KEY
      GENESIS_JSON: /upgrade/assets/genesis.json
      VERBOSITY: 3
      GASPRICE: 0
      GCMODE: full
      NO_USB: 'true'
      NO_DISCOVER: 'true'
      TARGET_GAS_LIMIT: 11000000
      USING_OVM: 'true'
      # L1
      ETH1_HTTP: $L1_HTTP_URL
      ETH1_CHAINID: $L1_CHAIN_ID
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      ETH1_SYNC_SERVICE_ENABLE: 'true'
      ETH1_CONFIRMATION_DEPTH: 0
      # Rollup
      ROLLUP_CLIENT_HTTP: $ORIGIN_DTL_URL
      ROLLUP_POLL_INTERVAL_FLAG: 1s
      ROLLUP_ENABLE_L2_GAS_POLLING: 'true'
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_BACKEND: l2
      ROLLUP_VERIFIER_ENABLE: 'true'
      # RPC
      RPC_ENABLE: 'true'
      RPC_ADDR: 0.0.0.0
      RPC_API: eth,web3,net
      RPC_CORS_DOMAIN: '*'
      RPC_VHOSTS: '*'
      # MISC
      DANGEROUS_UPDATE_CONTRACT: /upgrade/assets/contractupdate.json
      L2GETH_STATE_DUMP_PATH: /upgrade/data/state-dump.txt
    volumes:
      - ..:/opstack
      - .:/upgrade
      - ./data:/root/.ethereum

  op-migrate:
    <<: [*common, *oneshot]
    build:
      dockerfile: ./Dockerfile.op-migrate
    entrypoint: /bin/bash
    env_file: .env
    volumes:
      - ..:/opstack
      - .:/upgrade
